Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerce.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CategoryUnit { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace ECommerce.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ProductItem.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerce.Models
{
    public class ProductItem
    {
        [Key]
        public int ProductItemId { get; set; }
        public string ProductName { get; set; } 
        public string ProductCode { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public decimal UnitPrice { get; set; }
        public string Thumbnail { get; set; }
    }
}

Controllers/CategoryController.cs
using ECommerce.DataAccess;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    public class CategoryController : Controller
    {
        ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context) 
        { 
            _context = context;
        }
        public IActionResult Index()
        {
            /*Category c = new Category();
            c.CategoryName = "Shoes";
            c.CategoryUnit = "Unit";
            c.CreatedDate = DateTime.Now;
            _context.Add(c);
            _context.SaveChanges();*/

            var datas= _context.Category.ToList();
            return View(datas);
        }
        public JsonResult Save(string categoryName,string categoryCode,int id)
        {
            if(id == 0)
            {
                Category c = new Category()
                {
                    CategoryName = categoryName,
                    CategoryUnit = categoryCode,
                    CreatedDate = DateTime.Now,
                };
                _context.Category.Add(c);
                _context.SaveChanges();
                return Json(new
                {
                    success = true,
                    message = "Data Saved Successfully"
                });
            }
            else
            {
                var oldData = _context.Category.Where(x => x.Id == id).FirstOrDefault();
                if (oldData == null)
                {
                    return Json(new
                    {
                        success = false,
                        message = "Data Not Found"
                    });
                }
                else
                {
                    oldData.CategoryName = categoryName;
                    oldData.CategoryUnit = categoryCode;
                    oldData.CreatedDate = DateTime.Now;
                    _context.SaveChanges();
                    return Json(new
                    {
                        success = true,
                        message = "Succesfully Updated"
                    });
                }
            }
           
        }
        public JsonResult Delete(int id)
        {
           var data = _context.Category.Where(x => x.Id == id).FirstOrDefault();
            if(data == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Data Not Found"
                });
            }
            else
            {
               _context.Category.Remove(data);
               _context.SaveChanges();
                return Json(new
                {
                    success = true,
                    message = "Data Deleted Successfully"
                });
            }
        }

        public JsonResult Edit (int id)
        {
            var data = _context.Category.Where(x => x.Id==id).FirstOrDefault();
            if(data == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Data Not Found"
                });
            }
            else
            {
                return Json(new
                {
                    success = true,
                    data = data
                });
            }
        }
    }
}

Controllers/HomeController.cs
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ECommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductItemController.cs
using ECommerce.DataAccess;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    public class ProductItemController : Controller
    {
        ApplicationDbContext _context;
        public ProductItemController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var datas = _context.ProductItems.ToList();
            return View(datas);
        }
        public JsonResult Save(string name,string code,int categoryId,string description,int unitPrice,string thumbnail,int id)
        {
            if(id == 0)
            {
                ProductItem obj = new ProductItem()
                {
                    ProductName = name,
                    ProductCode = code,
                    CategoryId = categoryId,
                    Description = description,
                    UnitPrice = unitPrice,
                    Thumbnail = thumbnail
                };
                _context.ProductItems.Add(obj);
                _context.SaveChanges();
                return Json(new
                {
                    success = true,
                    message = "Product Item Saved Successfully"
                });
            }
            else
            {
                var oldData = _context.ProductItems.Where(x => x.ProductItemId == id).FirstOrDefault();
                if(oldData == null)
                {
                    return Json(new
                    {
                        success = false,
                        message = "Data Not Found"
                    });
                }
                else
                {
                    oldData.ProductName = name;
                    oldData.ProductCode = code;
                    oldData.Thumbnail = thumbnail;
                    oldData.Description = description;
                    oldData.UnitPrice = unitPrice;
                    oldData.CategoryId = categoryId;
                    _context.SaveChanges();
                    return Json(new
                    {
                        success= true,
                        message = "Data Updated Successfully"
                    });
                }
            }
            
        }

        public JsonResult Delete(int id)
        {
            var data = _context.ProductItems.Where(x => x.ProductItemId == id).FirstOrDefault();
            if(data == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Data Not Found"
                });
            }
            else
            {
                _context.ProductItems.Remove(data);
                _context.SaveChanges();
                return Json(new
                {
                    success = true,
                    message = "Data Deleted Successfully"
                });
            }
        }

        public JsonResult Edit(int id)
        {
            var data = _context.ProductItems.Where(x => x.ProductItemId == id).FirstOrDefault();
            if(data == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Data Not Found"
                });
            }
            else
            {
                return Json(new
                {
                    success = true,
                    data = data
                });
            }
        }
    }
}

Views/Category/Index.cshtml
@model IEnumerable<ECommerce.Models.Category>
<h1> This is Category Index</h1>
<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <table class="table table-hover">
                   <thead>
                       <th>Name</th>
                       <th>Unit</th>
                       <th>Action</th>
                   </thead>
                   <tbody>
                        @foreach(Category x in Model)
                        {
                            <tr>
                                <td>@x.CategoryName</td>
                                <td>@x.CategoryUnit</td>
                                <td>
                                    <button type="button" data-key="@x.Id" class="btn btn-primary btn-sm btnEdit">Edit</button>
                                    <button type="button" data-key="@x.Id" class="btn btn-danger btn-sm btnDelete">Delete</button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
               <div class="row">
                   <div class="col-md-3">
                       Name
                   </div>
                    <div class="col-md-9">
                        <input type="text" class="form-control formName"/>
                    </div>
               </div>
                <div class="row col mt-2">
                    <div class="col-md-3">
                        Code
                    </div>
                    <div class="col-md-9">
                        <input type="text" class="form-control formUnit"/>
                    </div>
                </div>
                <div class="row col mt-2">
                    <div class="col-md-3">
                    </div>
                    <div class="col-md-6">
                        <input type="hidden" class="hdnId"/>
                       <button type="button" class="btn btn-success btn-sm btnSave">Save</button>
                        <button type="button" class="btn btn-danger btn-sm btnCancel">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(document).ready(function () {
            toastr.success("Welcome");
        })
        $(document).on('click','.btnSave',function(){
            var hdnId = $('.hdnId').val() || 0;
            var name = $('.formName').val();
            var code = $('.formUnit').val();
            if (name == '') {
                toastr.error("Please Enter Name");
            } else if (code == '') {
                toastr.error("Please Enter Code");
            } else {
                $.ajax({
                    method:'get',
                    url:'@Url.Action("Save", "Category")?categoryName=' + name + '&categoryCode=' + code + '&id=' + hdnId,
                    contentType: "application/json;charset=utf-8",
                    success: function (res) {
                        toastr.success(res.message);
                        clearForm();
                    }
                })
            }
        })
        $(document).on('click', '.btnCancel', function () {
            Swal.fire({
                title: "Are you sure want to reset?",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, Reset it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $('.formName').val('');
                    $('.formUnit').val('');
                }
            });
        })
        $(document).on('click', '.btnDelete', function () {
            var id = $(this).data('key');
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        method: 'get',
                        url: '@Url.Action("Delete", "Category")?id=' + id,
                        contentType: "application/json;charset=utf-8",
                        success: function (res) {
                            toastr.success(res.message);
                        }
                    })
                }
            });
        })
        function clearForm() {
            $('.formName').val('');
            $('.formUnit').val('');
        }

        $(document).on('click','.btnEdit',function(){
            var id = $(this).data('key');
            debugger;
            $.ajax({
                method:'get',
                url: '@Url.Action("Edit", "Category")?id=' + id,
                contentType: "application/json;charset=utf-8",
                success: function (res) {
                    if (res.success) {
                        $('.formName').val(res.data.categoryName);
                        $('.formUnit').val(res.data.categoryUnit);
                        $('.hdnId').val(res.data.id);
                    }
                }
            })
        })
    </script>
}

Views/Home/Contact.cshtml
<h1>This is Contact Page</h1>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/ProductItem/Index.cshtml
@model IEnumerable<ECommerce.Models.ProductItem>
<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                        <th>Product Name</th>
                        <th>Product Code</th>
                        <th>Category Id</th>
                        <th>Description</th>
                        <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(ProductItem x in Model)
                        {
                            <tr>
                                <td>@x.ProductName</td>
                                <td>@x.ProductCode</td>
                                <td>@x.CategoryId</td>
                                <td>@x.Description</td>
                                <td>
                                    <button data-key="@x.ProductItemId" class="btn btn-primary btn-sm btnEdit">Edit</button>
                                    <button data-key="@x.ProductItemId" class="btn btn-danger btn-sm btnDelete">Delete</button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-5">
                        Product Name
                    </div>
                    <div class="col-md-7">
                        <input type="text" class="form-control txtProductName"/>
                    </div>
                </div>
                <div class="row col mt-2">
                    <div class="col-md-5">
                        Product Code
                    </div>
                    <div class="col-md-7">
                        <input type="text" class="form-control txtProductCode" />
                    </div>
                </div>
                <div class="row col mt-2">
                    <div class="col-md-5">
                        Category Id
                    </div>
                    <div class="col-md-7">
                        <input type="text" class="form-control txtCategoryId" />
                    </div>
                </div>
                <div class="row col mt-2">
                    <div class="col-md-5">
                        Description
                    </div>
                    <div class="col-md-7">
                        <input type="text" class="form-control txtDescription" />
                    </div>
                </div>
                <div class="row col mt-2">
                    <div class="col-md-5">
                        Unit Price
                    </div>
                    <div class="col-md-7">
                        <input type="number" class="form-control txtUnitPrice" />
                    </div>
                </div>
                <div class="row col mt-2">
                    <div class="col-md-5">
                        Thumbnail
                    </div>
                    <div class="col-md-7">
                        <input type="text" class="form-control txtThumbnail" />
                    </div>
                </div>
                <div class="row col mt-2">
                    <div class="col-md-5">
                    </div>
                    <div class="col-md-7">
                        <input type="hidden" class="hdnId"/>
                        <button type="button" class="btn btn-success btn-sm btnSave">Save</button>
                        <button type="button" class="btn btn-danger btn-sm btnReset">Reset</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(document).on('click', '.btnSave', function () {
            var id = $('.hdnId').val() || 0;
            var name = $('.txtProductName').val();
            var code = $('.txtProductCode').val();
            var categoryId = $('.txtCategoryId').val();
            var description = $('.txtDescription').val();
            var unitPrice = $('.txtUnitPrice').val();
            var thumbnail = $('.txtThumbnail').val();
            if (name == '') {
                toastr.error("Please Enter Product Name");
            }
            else if (code == '') {
                toastr.error("Please Enter Product Code");
            }
            else if (categoryId == '') {
                toastr.error("Please Enter Category Id");
            }
            else if (description == '') {
                toastr.error("Please Enter Description");
            }
            else if (unitPrice == '') {
                toastr.error("Please Enter Unit Price");
            }
            else if (thumbnail == '') {
                toastr.error("Please Enter Thumbnail");
            }
            else {
                $.ajax({
                    method:'get',
                    url:'@Url.Action("Save","ProductItem")?name=' + name + '&code=' + code + '&categoryId=' + categoryId + '&description=' + description + '&unitPrice=' + unitPrice + '&thumbnail=' + thumbnail + '&id=' + id,
                    contentType: "application/json;charset=utf-8",
                    success: function (res) {
                        toastr.success(res.message);
                        clearForm();
                    }
                })
            }
        })

        $(document).on('click', '.btnReset', function () {
            Swal.fire({
                title: "Are you sure you want to reset?",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, Reset it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $('.txtProductName').val('');
                    $('.txtProductCode').val('');
                    $('.txtCategoryId').val('');
                    $('.txtDescription').val('');
                    $('.txtUnitPrice').val('');
                    $('.txtThumbnail').val('');
                }
            });
        })

        function clearForm() {
            $('.txtProductName').val('');
            $('.txtProductCode').val('');
            $('.txtCategoryId').val('');
            $('.txtDescription').val('');
            $('.txtUnitPrice').val('');
            $('.txtThumbnail').val('');
        }

        $(document).on('click', '.btnDelete', function () {
            var id = $(this).data('key');
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        method: 'get',
                        url: '@Url.Action("Delete", "ProductItem")?id=' + id,
                        contentType: "application/json;charset=utf-8",
                        success: function (res) {
                            toastr.success(res.message);
                        }
                    })
                }
            });
        })

        $(document).on('click', '.btnEdit', function () {
            var id = $(this).data('key');
            $.ajax({
                method: 'get',
                url: '@Url.Action("Edit", "ProductItem")?id=' + id,
                contentType: "application/json;charset=utf-8",
                success: function (res) {
                    if(res.success){
                        $('.hdnId').val(res.data.productItemId);
                        $('.txtProductName').val(res.data.productName);
                        $('.txtProductCode').val(res.data.productCode);
                        $('.txtCategoryId').val(res.data.categoryId);
                        $('.txtDescription').val(res.data.description);
                        $('.txtUnitPrice').val(res.data.unitPrice);
                        $('.txtThumbnail').val(res.data.thumbnail);
                    }
                }
            })
        })
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductItem" asp-action="Index">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ECommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>